version: '3.8'
services:
  web:
    build: .
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - mysql8
    environment:
      DATABASE_URL: mysql://user:1234@mysql8/sila
    networks:
      - net-db

  mysql8:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sila
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    networks:
      - net-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql8
      PMA_USER: user
      PMA_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    depends_on:
      - mysql8
    networks:
      - net-db

networks:
  net-db:
    external: true
